// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHPBKdrPyAWKZugpCN-KpPjA0KbsACx3A',
    appId: '1:16100501076:web:38dbf03dd6188948462fc1',
    messagingSenderId: '16100501076',
    projectId: 'trabcon-kamide',
    authDomain: 'trabcon-kamide.firebaseapp.com',
    storageBucket: 'trabcon-kamide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAFXd9gp8YPBd4dk-354mDiwGb33tGKg',
    appId: '1:16100501076:android:d2fa95865f678338462fc1',
    messagingSenderId: '16100501076',
    projectId: 'trabcon-kamide',
    storageBucket: 'trabcon-kamide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5Enn7u6ArBx0yDK5QBWqNnCEgITx6M8',
    appId: '1:16100501076:ios:fb10bb06dd6a07aa462fc1',
    messagingSenderId: '16100501076',
    projectId: 'trabcon-kamide',
    storageBucket: 'trabcon-kamide.appspot.com',
    iosClientId: '16100501076-k42r2dfupqmn8gdoe8gqise5uftg59ds.apps.googleusercontent.com',
    iosBundleId: 'com.gibalmeida.trabcon-app',
  );
}
